services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: triosigno

    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d triosigno"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: trio-signo-server/.
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/triosigno?schema=public
    networks:
      - mynetwork
    entrypoint: ["/bin/sh", "-c", "echo $DATABASE_URL && npx prisma migrate deploy && npm run start:prod"]


  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - mynetwork

  ai-service:
    build: trio-signo-ai/.
    ports:
      - "5000:5000"
    depends_on:
      - server
    networks:
      - mynetwork

  front-service:
    build: trio-signo-front/.
    ports:
      - "80:4000"
      - "4000:4000"
    depends_on:
      - server
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  pgdata:
