services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    expose:
      - "5432"  # ⚠️ only visible to other services in the same network
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: triosigno
    secrets:
      - db_password
    networks:
      - private
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d triosigno"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: ./trio-signo-server
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "3000"  # only visible to other services in the same network
    depends_on:
      db:
        condition: service_healthy
    networks:
      - private
      - web
    entrypoint: ["/bin/sh", "-c", 'echo "📦 DATABASE_URL=$DATABASE_URL" && env && npx prisma migrate deploy && npm run start:prod']

  ai-service:
    build: ./trio-signo-ai
    restart: unless-stopped
    expose:
      - "5000"
    depends_on:
      - server
    networks:
      - private
      - web

  front-service:
    build: ./trio-signo-front
    restart: unless-stopped
    expose:
      - "4000"
    depends_on:
      - server
    networks:
      - private
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`triosigno.local`)"
      - "traefik.http.routers.front.entrypoints=web"
      - "traefik.http.services.front.loadbalancer.server.port=4000"

  reverse-proxy:
    image: traefik:v3.3
    restart: unless-stopped
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=triosignoapp@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    networks:
      - web

secrets:
  db_password:
    file: ./secrets/db_password.txt

volumes:
  pgdata:
  letsencrypt:

networks:
  private:
    name: triosigno_private
    internal: true
  web:
    name: triosigno_web

