version: '3.8'

services:
  server:
    build: trio-signo-server/.
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/triosigno
    networks:
      - mynetwork
    entrypoint: ["/bin/sh", "-c", "npx prisma migrate deploy && npm run start:prod"]

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: triosigno
    networks:
      - mynetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  ai-service:
    build: trio-signo-ai/.
    ports:
      - "5000:5000"
    depends_on:
      - server
    networks:
      - mynetwork

networks:
  mynetwork:
