name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: srv730768
    if: github.repository == 'EIP-TEK89/trio-signo-fullstack'
    steps:
      - uses: actions/checkout@v4.1.5

      - name: Set variables
        run: |
          export XDG_RUNTIME_DIR="/run/user/$UID"
          export DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus"

      - name: Create folder in case not created
        run: |
          cd /home/triosigno/
          mkdir -p triosigno-server
          cd ${GITHUB_WORKSPACE}

      - name: Stopping server
        run: |
          cd /home/triosigno/triosigno-server
          sudo docker compose down || true
          cd ${GITHUB_WORKSPACE}

      - name: Copy files to Service folder
        run: |
          cp -rf .[!.]* * /home/triosigno/triosigno-server

      - name: Cloning or updating sub-modules
        run: |
          cd /home/triosigno/triosigno-server
          git submodule update --init --recursive
          git submodule update --remote --merge
          cd ${GITHUB_WORKSPACE}

      - name: Restart docker
        run: |
          cd /home/triosigno/triosigno-server
          sudo docker compose up --detach
          cd ${GITHUB_WORKSPACE}
