name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy over SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            # Si le dossier n'existe pas, on clone le projet
            if [ ! -d "/home/deploy/trio-signo-fullstack" ]; then
              git clone https://github.com/EIP-TEK89/trio-signo-fullstack.git /home/deploy/trio-signo-fullstack
            fi

            cd /home/deploy/trio-signo-fullstack

            # Met à jour avec les submodules
            git pull --recurse-submodules
            git submodule update --remote --merge

            # Build & run
            docker compose down
            docker compose pull
            docker compose up -d --build
          EOF
