name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: srv730768
    if: github.repository == 'EIP-TEK89/trio-signo-fullstack'
    steps:
      - uses: actions/checkout@v4.1.5

      - name: Set variables
        run: |
          export XDG_RUNTIME_DIR="/run/user/$UID"
          export DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus"

      - name: Create folder in case not created
        run: mkdir -p /home/$USER/triosigno-server

      - name: Stopping server
        run: |
          cd /home/$USER/triosigno-server
          sudo docker composer down || true
          cd ${GITHUB_WORKSPACE}

      - name: Copy files to Service folder
        run: |
          cp -rf . /home/$USER/triosigno-server

      - name: Restart docker
        run: |
          cd /home/$USER/triosigno-server
          sudo docker up --detach
          cd ${GITHUB_WORKSPACE}
