name: Mirror Repository

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Nécessaire pour `git push --mirror`

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Mirror Push to Target Repository
        run: |
          git remote add mirror https://<Linnchoeuh>:${{ secrets.GIT_MIRROR_PAT }}@github.com/EpitechPromo2026/G-EIP-700-PAR-7-1-eip-valentin1.maurel.git
          git push --mirror mirror
