name: Mirror Repository

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    if: github.repository == 'EIP-TEK89/trio-signo-fullstack'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Nécessaire pour `git push --mirror`

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Mirror Push to Target Repository
        run: |
          git remote add mirror git@github.com:EpitechPromo2026/G-EIP-700-PAR-7-1-eip-valentin1.maurel.git
          git push --mirror mirror
